[package]
name = "noir_safe_account_proof_circuit"
type = "bin"
authors = ["chiefbiiko"]
compiler_version = ">=0.30.0"

[dependencies]
noir_trie_proofs = { git = "https://github.com/chiefbiiko/noir-trie-proofs", tag = "explicit-numeric-generics", directory = "lib" }