#TODO
    # sp_vk : [Field; 114],
    # sp_vk_hash : Field,
    # sp_proof : [Field; 93],
    # sp_pi : [Field; 1],
    # ap_vk : [Field; 114],
    # ap_vk_hash : Field,
    # ap_proof : [Field; 93],
    # ap_pi : [Field; 1],