[package]
name = "circuits"
type = "bin"
authors = ["chiefbiiko"]
compiler_version = ">=0.30.0"

[dependencies]
noir_trie_proofs = { git = "https://github.com/aragonzkresearch/noir-trie-proofs.git", rev = "cfaba4e", directory = "lib" }